### ISSUE TITLE
Same blog with updated packages?

### ISSUE THREAD

**Issue by eminfedar** [Harrison1/unrealcpp-com#1]
Hi, can you upgrade this blog's dependencies to the latest gatsby versions? It is very nice blog architecture to use but very old.

Thanks!

**Comment by Harrison1** [comment]
yo, thanks for reaching out. My fault on being super late. I just updated this repo to gatsby v3. The repo is far from perfect, there are plenty of things that can be improved, but hopefully it can be good starting point.
